program: scripts/train.py
method: bayes
metric:
  name: val_mAP
  goal: maximize
parameters:
  model:
    value: lgbm
  n_estimators:
    values: [100, 200, 400]
  max_depth:
    values: [-1, 6, 10]
  learning_rate:
    distribution: log_uniform_values
    min: 0.01
    max: 0.3
